const data = 
  {
      "totalCaloriesBurnt":13500,
      "totalWorkouts":6,
      "avgCaloriesBurntPerWorkout":2250,
      "totalWeeksCaloriesBurnt":{
          "weeks":[
              "17th",
              "18th",
              "19th",
              "20th",
              "21th",
              "22th",
              "23th"
          ],
          "caloriesBurned":[
              10500,
              5000,
              20000,
              5555,
              0,
              1010,
              0,
              20000
          ]
      },

      "pieChartData":[
          {
          "id":0,
          "value":2020,
          "label":"Legs"
           },
          {
          "id":2,
          "value":1212,
          "label":"Back"
           },
          {
          "id":0,
          "value":300,
          "label":"Shoulder"
           },
          {
          "id":0,
          "value":800,
          "label":"Abs"
           }
  ] }